export {
  schoolLogin,
  getDashboardSummary,
  listPlacements,
  uploadPlacements,
  syncPlacementsToStudents,
  listStudentRecords,
  getAssignmentData,
  assignHousesAndClasses,
  updateSchoolSettings,
  createDocumentUploadUrl,
  finalizeDocumentUpload,
  updateInstitutionProfile,
  listHousesAndClasses,
  saveHouse,
  deleteHouse,
  saveClass,
  deleteClass,
  setAdmissionCycle,
  clearCycleData,
} from "@/lib/portal-api";
