import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";

const sb = supabase as any;

export interface StudentRow {
  id: string;
  student_id: string;
  name: string;
  class_id: string | null;
  program: string | null;
  status: string;
  residency?: string;
  is_scholarship?: boolean;
  is_free_shs?: boolean;
  department_id?: string | null;
  department_name?: string;
  created_at: string;
  class_name?: string;
  parent_name?: string;
  parent_phone?: string;
  parent_phone_secondary?: string;
  tags?: string[];
  pin?: string;
}

export function useStudents() {
  return useQuery({
    queryKey: ["students"],
    queryFn: async () => {
      const { data, error } = await sb
        .from("students")
        .select(`*, classes(name), departments(name), parents(name, phone, phone_primary, phone_secondary_2), student_tags(tag), student_pins(pin_plain)`)
        .order("created_at", { ascending: false });
      if (error) throw error;
      return (data || []).map((s: any) => ({
        id: s.id,
        student_id: s.student_id,
        name: s.name,
        class_id: s.class_id,
        program: s.program,
        status: s.status,
        residency: s.residency,
        is_scholarship: s.is_scholarship,
        is_free_shs: s.is_free_shs,
        department_id: s.department_id,
        department_name: s.departments?.name || "",
        created_at: s.created_at,
        class_name: s.classes?.name || "",
        parent_name: s.parents?.[0]?.name || "",
        parent_phone: s.parents?.[0]?.phone_primary || s.parents?.[0]?.phone || "",
        parent_phone_secondary: s.parents?.[0]?.phone_secondary_2 || "",
        tags: (s.student_tags || []).map((t: any) => t.tag),
        pin: s.student_pins?.[0]?.pin_plain || "",
      })) as StudentRow[];
    },
  });
}

export function useAddStudent() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (input: {
      name: string;
      class_id: string | null;
      program: string;
      department_id?: string | null;
      parent_name: string;
      parent_phone: string;
      parent_phone_secondary?: string;
      residency?: "Day" | "Boarding";
      is_scholarship?: boolean;
      is_free_shs?: boolean;
      academic_year?: string;
      tags: string[];
    }) => {
      // student_id is auto-generated by DB trigger
      const { data: student, error } = await sb
        .from("students")
        .insert({
          name: input.name,
          class_id: input.class_id,
          program: input.program,
          department_id: input.department_id || null,
          residency: input.residency || "Day",
          is_scholarship: input.is_scholarship || false,
          is_free_shs: input.is_free_shs || false,
          academic_year: input.academic_year || null,
        })
        .select(`*, student_pins(pin_plain)`)
        .single();
      if (error) throw error;

      if (input.parent_name && input.parent_phone) {
        await sb.from("parents").insert({
          student_id: student.id,
          name: input.parent_name,
          phone: input.parent_phone,
          phone_primary: input.parent_phone,
          phone_secondary_2: input.parent_phone_secondary || null,
        });
      }

      if (input.tags.length > 0) {
        await sb.from("student_tags").insert(
          input.tags.map((tag) => ({ student_id: student.id, tag }))
        );
      }

      return student;
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["students"] }),
  });
}

export function useDeleteStudent() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await sb.from("students").delete().eq("id", id);
      if (error) throw error;
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["students"] }),
  });
}
