
INSERT INTO sms_templates (name, body) VALUES
 ('A1. School General Notice','Dear Parent, this is to inform you of an important school update. Kindly contact the school for details. Thank you.'),
 ('A2. Holiday Notice','Dear Parent, school will close on {Date} and resume on {ResumeDate}. Kindly ensure your ward returns promptly.'),
 ('A3. PTA Meeting','Dear Parent, you are invited to a PTA meeting on {Date} at {Time}. Your presence is highly appreciated.'),
 ('B1. Fee Reminder (Soft)','Dear {ParentName}, this is a reminder that {StudentName} has an outstanding fee balance of GHS {Amount}. Kindly settle at your earliest convenience.'),
 ('B2. Fee Reminder (Firm)','Dear {ParentName}, {StudentName} owes GHS {Amount}. Kindly clear this before {Deadline} to avoid inconvenience.'),
 ('B3. Exam Clearance Warning','Dear {ParentName}, {StudentName} will not be allowed to write exams unless outstanding fees of GHS {Amount} are cleared.'),
 ('B4. Payment Confirmation','Dear {ParentName}, payment of GHS {Amount} for {StudentName} has been received. Thank you.'),
 ('B5. Part Payment Acknowledgment','Dear {ParentName}, we acknowledge receipt of GHS {AmountPaid}. Outstanding balance: GHS {Balance}. Thank you.'),
 ('B6. Payment Plan Reminder','Dear {ParentName}, kindly honour your payment agreement for {StudentName}. Next payment is due on {Date}.'),
 ('B7. Chronic Debtor Notice','Dear {ParentName}, despite previous reminders, {StudentName} still owes GHS {Amount}. Kindly visit the school immediately.'),
 ('C1. Exam Start Notice','Dear Parent, exams begin on {Date}. Ensure your ward is punctual and prepared.'),
 ('C2. Exam Timetable Reminder','Dear Parent, please ensure {StudentName} follows the exam timetable strictly. Contact school for details if needed.'),
 ('C3. Results Notification','Dear {ParentName}, results for {StudentName} are available. Please visit the school or portal to access them.'),
 ('C4. Performance Update','Dear {ParentName}, {StudentName} scored {Score}% in {Subject}. Kindly encourage improvement.'),
 ('D1. Absentee Alert','Dear {ParentName}, {StudentName} was absent from school today. Kindly follow up.'),
 ('D2. Late Coming','Dear {ParentName}, {StudentName} reported late to school today. Please take note.'),
 ('D3. Misconduct Notice','Dear {ParentName}, {StudentName} was involved in misconduct. Kindly visit the school for discussion.'),
 ('E1. School Event','Dear Parent, you are invited to {EventName} on {Date}. We look forward to your participation.'),
 ('E2. Sports Notification','Dear Parent, {StudentName} has been selected for {Event}. Kindly support participation.'),
 ('F1. Admission Open','Admissions are open for {AcademicYear}. Enroll now at {SchoolName}. Contact {Phone}.'),
 ('F2. Promotion Campaign','Give your ward quality education at {SchoolName}. Limited spaces available. Call now!'),
 ('G1. Urgent Notice','Dear Parent, there is an urgent school update. Kindly contact the school immediately.'),
 ('G2. Health Alert','Dear Parent, please take note of a health advisory issued by the school. Contact us for details.');
